# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c0300dc03a97015e002d9e958dc09c835d05ca335806d0e394d307661dc88613e0088a6bcf7bdc264f81c6d887f1f566143bea0674a4eeb4ab560db896a638a
  domain: mickey.com
test:
  secret_key_base: babf3aef5e4479c5b3f2119f3a5a05b8162850047d183db016f219a720d740cb9d22e8f6eae929d52120f486c639a720d9a9ca8bf7a811eddc08c11d8396a1bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
